export const SET_SETTINGS_DISPLAY_VALUE = 'SET_SETTINGS_DISPLAY_VALUE'
export const ADD_NODE_AT_INDEX = 'ADD_NODE_AT_INDEX'
export const REMOVE_NODE_AT_INDEX = 'REMOVE_NODE_AT_INDEX'
export const SET_CORE_GRID_SETTINGS_CSS_VALUES = 'SET_CORE_GRID_SETTINGS_CSS_VALUES'
